In [179]:
import pickle

In [180]:
car_dict = {
    "Levy": 1399,
    "Manufacturer": "LEXUS",
    "Model": "RX 450",
    "Prode. year": 2010,
    "Category": "Jeep",
    "Leather interior": "Yes",
    "Fuel type": "Hybrid",
    "Engine volume": 3.5,
    "Mileage": 150000,
    "Cylinders": 6.0,
    "Gear box type": "Automatic",
    "Drive wheels": "4x4",
    "Wheel": "Left wheel",
    "Color": "Silver",
    "Airbags": 12
}

# Preprocessing Plan for Model Input

## Input Handling
- Ensure proper handling of input features in
`replace_categorical_by_numerical`:
    - **Engine Volume**: Accept as a numerical input.
    - **Levy**: Input as a number: if not provided, use `0` as the default
    value.
    - **Mileage**: Input as a numerical value.

## Feature Engineering
- Generate a new feature: **`Age`** (e.g., from the car's manufacturing year).

## Feature Removal
- Remove the feature: **`ID`, `Doors`, `Prod. year`** from the dataset.

In [181]:
import pandas as pd
data = pd.DataFrame([car_dict])
data

,Levy,Manufacturer,Model,Prode. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Wheel,Color,Airbags
0,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,150000,6.0,Automatic,4x4,Left wheel,Silver,12

In [182]:
from datetime import datetime

data['Age'] = datetime.now().year - data['Prode. year']

data = data.drop(['Prode. year'], axis=1)

In [183]:
data

,Levy,Manufacturer,Model,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Wheel,Color,Airbags,Age
0,1399,LEXUS,RX 450,Jeep,Yes,Hybrid,3.5,150000,6.0,Automatic,4x4,Left wheel,Silver,12,16

In [184]:
one_hot_columns = ['Leather interior', 'Gear box type', 'Drive wheels', 'Wheel']

with open('../models/one_hot_encoder.pkl', 'rb') as f:
    one_hot_encoder = pickle.load(f)

encoded_data = one_hot_encoder.transform(data[one_hot_columns])
encoded_data_df = pd.DataFrame(
    encoded_data,
    columns=one_hot_encoder.get_feature_names_out(one_hot_columns),
    index=data.index
)

data = pd.concat([data, encoded_data_df], axis=1)
data.drop(columns=one_hot_columns, inplace=True)

In [185]:
data

,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Cylinders,Color,Airbags,...,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
0,1399,LEXUS,RX 450,Jeep,Hybrid,3.5,150000,6.0,Silver,12,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [186]:
label_encode_columns = ['Fuel type', 'Category', 'Model', 'Color', 'Manufacturer']

with open('../models/label_encoders.pkl', 'rb') as f:
    label_encoders = pickle.load(f)
    
for column in label_encode_columns:
    le = label_encoders[column]
    data[column] = le.transform(data[column])

In [187]:
data

,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Cylinders,Color,Airbags,...,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
0,1399,28,1073,4,2,3.5,150000,6.0,12,12,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [188]:
numerical_columns = ['Levy', 'Engine volume', 'Mileage', 'Age']

with open('../models/scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

data[numerical_columns] = scaler.transform(data[numerical_columns])

In [189]:
data

,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Cylinders,Color,Airbags,...,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
0,1.76807,28,1073,4,2,2.199085,0.245158,6.0,12,12,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [190]:
with open('../models/model.pkl', 'rb') as f:
    model = pickle.load(f)

In [191]:
model.predict(data)

array([9489.91528926])